### ISSUE TITLE
latest debian/changelog entry has wrong month syntax

### ISSUE THREAD

**Issue by redrattus** [open-switch/opx-tools#23]
Latest debian/changelog entry has wrong month syntax. March should be changed to Mar. Otherwise building of Debian package complains:

 -- Dell EMC <ops-dev@lists.openswitch.net>  Mon, 18 March 2019 16:32:35 -0700
...
 -- Dell EMC <ops-dev@lists.openswitch.net>  Wed, 13 March 2019 10:32:35 -0700
...

**Comment by jeffyin-dell** [comment]
https://github.com/open-switch/opx-tools/pull/25
