### ISSUE TITLE
opx-config-interface not working out of the box

### ISSUE THREAD

**Issue by grantcurell** [open-switch/opx-tools#26]
I might be something really silly, but I just set up a new installation of opx on a Dell 4112F-ON. I did notice the version info is a bit strange:

    OS_NAME="OPX"
    OS_VERSION="unstable"
    PLATFORM="S4112F-ON"
    ARCHITECTURE="x86_64"
    INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
    BUILD_VERSION="unstable.0-stretch"
    BUILD_DATE="2019-06-21T19:04:22+0000"
    INSTALL_DATE="2019-10-23T23:16:10+00:00"
    SYSTEM_UPTIME= 1 day, 5 minutes
    SYSTEM_STATE= running
    UPGRADED_PACKAGES=no
    ALTERED_PACKAGES=yes

I swap over to root and try to configure an interface and get:

```
root@OPX:~# opx-config-interface --port e101-001-0 --autoneg off --speed 1G --duplex full --fec auto
Traceback (most recent call last):
  File "/usr/bin/opx-config-interface", line 68, in <module>
    print 'Failed to set port {}'.format(port) >> sys.stderr
TypeError: unsupported operand type(s) for >>: 'str' and 'file'
```

**Comment by grantcurell** [comment]
Just troubleshot a bit, it's `--fec auto` that's causing the problem. I pulled the command from the documentation [here](https://github.com/open-switch/opx-docs/wiki/opx-config-interface). If I get the chance I'll check it out in a debugger.

**Comment by gunasekaran-t** [comment]
@grantcurell yes, the issue is setting fec value. Not all interfaces support fec, hence trying to set for interfaces that doesnt support results in error. For interfaces that doesnt support FEC it will be off by default, and Auto for interfaces that support FEC. You can check it with opx-show-interface command.
