### ISSUE TITLE
Unable to bring slave interfaces up after creating lag via opx-config-lag tool.

### ISSUE THREAD

**Issue by philip1** [open-switch/opx-tools#8]
OPX3.1 

Testing was done on two S3048-ON and via virtual environment with same issue.

commands used:

opx-config-lag create --name bond1  --unblockedports e101-001-0..e101-002-0 --enable

ip l set dev dummy-bo-58 up
ip l set dev e101-001-0 up
ip l set dev e101-001-0 up

FYI- I know the physical connections are fine.
•	Links come up fine when using the cps_config_lag.py
•	Links come up fine when bond configured via Linux tools.

I've attached the logs from the two S3048-ON switches

[OPX-A.txt](https://github.com/open-switch/opx-tools/files/2760471/OPX-A.txt)
[OPX-B.txt](https://github.com/open-switch/opx-tools/files/2760472/OPX-B.txt)

-Thanks Phil

**Comment by atanu-mandal** [comment]
Closing this issue. Please reopen if the issue appears.
